name: npm build and publish

on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build and Deploy NPM
    steps:
      - uses: actions/checkout@v4

      - id: foo
        uses: tzahibar/npm_action@main
        with:
          deployer: 'tzahi_npm_test'
          resolver: 'tzahi_npm_remote_test'