name: npm build and publish

on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Build and Deploy NPM
    steps:
      - uses: actions/checkout@v4

      - name: Setup up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name : Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - id: foo
        uses: tzahibar/npm_action@main
        with:
          version: '1.0.0'
          deployer: 'tzahi_npm_test'
          resolver: 'tzahi_npm_remote_test'
          build_name: 'test'
          build_number: '1.0.0'
          server_id: 'ghplay'
          rt_url: ${{ secrets.ARTIFACTORY_URL }}
          rt_access_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          user: 'admin'